# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  directories: # Job that list subdirectories
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} # generate output name dir by using inner step output
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs
        run: |
          cd ./plugins
          echo "::set-output name=dir::$(ls -d */ | jq -R -s -c 'split("\n")[:-1]')"

  buildPlugins: # Loops all directories and builds plugins
    if: ${{ github.event_name == 'push'}}
    runs-on: ubuntu-latest
    container: srclosson/grafana-plugin-ci-alpine:latest
    needs: [directories]
    strategy:
      matrix:
        dir: ${{ fromJson(needs.directories.outputs.dir) }}
    defaults:
      run: # Defaults for all run steps, not uses
        working-directory: ./plugins/${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (yarn)
        run: |
          mkdir ci
          yarn install --frozen-lockfile

      - name: Lint fix
        run: yarn format

      - name: Build and test frontend
        run: ./node_modules/.bin/grafana-toolkit plugin:ci-build

      - name: Move results to ci folder
        run: ./node_modules/.bin/grafana-toolkit plugin:ci-build --finish

      - name: Package plugin
        run: ./node_modules/.bin/grafana-toolkit plugin:ci-package

      - name: Sign plugin
        run: npx @grafana/toolkit plugin:sign --rootUrls http://localhost:5600,https://dashboard.galibo.governify.io,https://dashboard.bluejay.governify.io
        working-directory: ./plugins/${{ matrix.dir }}/ci

      - name: Persist to workspace
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./plugins/${{ matrix.dir }}ci/jobs/package
            ./plugins/${{ matrix.dir }}ci/packages
            ./plugins/${{ matrix.dir }}ci/dist
            ./plugins/${{ matrix.dir }}ci/grafana-test-env

  buildProd:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push'}}
    needs: buildPlugins
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: governify/dashboard:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  
  buildTest:
    if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
    needs: buildPlugins
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: governify/dashboard:develop
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}